apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: monitoring-prom-pod
  labels:
    app: monitoring-prom-pod
spec:
  selector:
    matchLabels:
      monitoring: "true"
      app: monitoring-prom-pod
  podMetricsEndpoints:
  - port: web