apiVersion: v1
kind: Pod
metadata:
  name: monitoring-prom-pod
  labels:
    monitoring: "true"
    app: "monitoring-prom-pod"
spec:
  containers:
  - name: my-app
    image: fabxc/instrumented_app
    ports:
    - name: web
      containerPort: 8080