apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
   name: pvc1
spec: 
   accessModes: 
     - ReadWriteOnce 
   storageClassName: manual 
   resources: 
     requests: 
       storage: 100Mi 
   volumeName: pv1