apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-test-admin
  namespace: ns-test
subjects:
- kind: User
  name: david
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: admin-of-ns-test
  apiGroup: rbac.authorization.k8s.io