apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  labels:
    <labels>
spec:
  selector:
    matchLabels:
      run: kuard
  template:
    metadata:
      labels:
        run: kuard
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:blue
        ports:
          - containerPort: 8080
